name: voice_defender
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_background_service: ^5.0.2
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.15
  file_picker: ^6.0.0
  rxdart: ^0.27.7
  dio: ^5.3.3
  get: ^4.6.5
  curved_navigation_bar: ^1.0.3
  lottie: ^2.7.0
  flutter_slidable: ^3.0.1
  sqflite: ^2.3.0
  intl: ^0.18.1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  
    - assets/data/
    - assets/lottie/
    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cafe
      fonts:
        - asset: assets/font/Cafe24Ssurround-v2.0.ttf

    - family: Jamsil
      fonts:
        - asset: assets/font/The Jamsil 1 Thin.ttf
        - asset: assets/font/The Jamsil 2 Light.ttf
        - asset: assets/font/The Jamsil 3 Regular.ttf
        - asset: assets/font/The Jamsil 4 Medium.ttf
        - asset: assets/font/The Jamsil 5 Bold.ttf
        - asset: assets/font/The Jamsil 6 ExtraBold.ttf
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
