name: voice_defender
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_background_service: ^5.0.2
  smooth_page_indicator: ^1.0.0+2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.15
  file_picker: ^6.0.0
  rxdart: ^0.27.7
  dio: ^5.3.3
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

